# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
